blist/urls.py
from django.conf.urls import patterns, url

from blist import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^favorites/$', views.index, {'faves':True}, name='favorites'),
	url(r'^shared/$', views.shared_index, name='shared'),
	url(r'^shared/(?P<bucket_id>\d+)/$', views.shared_list, name='shared_list'),
	url(r'^shared/(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/$', views.shared_detail, name='shared_detail'),
	url(r'^(?P<bucket_id>\d+)/$', views.items, name='items'),
	url(r'^(?P<bucket_id>\d+)/share/$', views.share, name='share'),
	url(r'^(?P<bucket_id>\d+)/add_editor/$', views.add_editor, name='add_editor'),		
	url(r'^(?P<bucket_id>\d+)/delete_bl/$', views.delete_bucket, name='delete_bucket'),	
	url(r'^(?P<bucket_id>\d+)/mod_fav_bl/$', views.mod_favorite, name='mod_fav_bl'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_url/$', views.xu_url, name='xu_url'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_name/$', views.xu_name, name='xu_name'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_desc/$', views.xu_desc, name='xu_desc'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_date/$', views.xu_date, name='xu_date'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/delete/$', views.delete_item, name='delete_item'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/finish/$', views.finish, name='finish'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/$', views.details, name='details'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/share/$', views.share_details, name='sdetails'),
)

bucketlist/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

from blist import views

urlpatterns = patterns('',
    url(r'^login/', login),
    url(r'^logout/', logout, {'next_page': '/login/'}),
    url(r'^register/', views.register),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blist/', include('blist.urls', namespace="blist")),
	url(r'^search/$', views.search, name='search'),
)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Bucket List{% block title %}{% endblock %}</title>
    {% include 'head.html' %}
    {% block head %}{% endblock %}
</head>

<body>
    {% include 'nav.html' %}

    <div class='container'>
        <div class='row'>
            {% if user.is_authenticated %}
            <div class='col-md-2'></div>
            <div class='col-md-8'>
                {% block content %}{% endblock %}
            </div>
            <div class='col-md-2'></div>
            {% else %}
                {% block anon %}{% endblock %}
            {% endif %}
        </div>
    </div>

<!-- Additional Javascript -->
{% if user.is_authenticated %}
<script>
var ivals = {{ source|safe }};

$("#autocomplete").autocomplete({
    source: ivals
});
</script>
{% endif %}
</body>

</html>

templates/head.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-editable.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/moment.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/bl.js"></script>

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery-ui.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery-ui.structure.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery-ui.theme.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.theme.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap-editable.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css">

templates/nav.html
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-target=".bs-navbar-collapse" data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/blist/">Bucket List</a>
        </div>

        <div class="collapse navbar-collapse bs-navbar-collapse">
            {% if user.is_authenticated %}
            <div class="navbar-text">
                Hello {{ user.username }}!
            </div>
            
            <ul class='nav navbar-nav'>
                <li><a href="{% url 'blist:favorites' %}"><span class="glyphicon glyphicon-star"></span> Favorites</a></li>
                <li><a href="/blist/"><span class="glyphicon glyphicon-list"></span> My Lists</a></li>
                <li><a href="{% url 'blist:shared' %}"><span class="glyphicon glyphicon-transfer"></span> Shared Lists</a></li>
            </ul>

            <form action="/search/" method="get" class='navbar-form navbar-left' role='search'>
                <div class='input-group'>
                    <input type='text' name='q' id='autocomplete' class='form-control' placeholder='Search'>
                    <span class='input-group-btn'>
                        <button type='submit' class='btn btn-default'><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </form>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                {% else %}
                <li><a href="/register/"><span class="glyphicon glyphicon-user"></span> Register</a></li>
                <li><a href="/login/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>