blist/urls.py
from django.conf.urls import patterns, url

from blist import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^favorites/$', views.index, {'faves':True}, name='favorites'),
	url(r'^shared/$', views.shared_index, name='shared'),
	url(r'^shared/(?P<bucket_id>\d+)/$', views.shared_list, name='shared_list'),
	url(r'^shared/(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/$', views.shared_detail, name='shared_detail'),
	url(r'^(?P<bucket_id>\d+)/$', views.items, name='items'),
	url(r'^(?P<bucket_id>\d+)/share/$', views.share, name='share'),
	url(r'^(?P<bucket_id>\d+)/add_editor/$', views.add_editor, name='add_editor'),		
	url(r'^(?P<bucket_id>\d+)/delete_bl/$', views.delete_bucket, name='delete_bucket'),	
	url(r'^(?P<bucket_id>\d+)/mod_fav_bl/$', views.mod_favorite, name='mod_fav_bl'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_url/$', views.xu_url, name='xu_url'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_name/$', views.xu_name, name='xu_name'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_desc/$', views.xu_desc, name='xu_desc'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/xu_date/$', views.xu_date, name='xu_date'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/delete/$', views.delete_item, name='delete_item'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/finish/$', views.finish, name='finish'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/$', views.details, name='details'),
	url(r'^(?P<bucket_id>\d+)/(?P<item_id>\d+)/details/share/$', views.share_details, name='sdetails'),
)

bucketlist/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

from blist import views

urlpatterns = patterns('',
    url(r'^login/', login),
    url(r'^logout/', logout, {'next_page': '/login/'}),
    url(r'^register/', views.register),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blist/', include('blist.urls', namespace="blist")),
	url(r'^search/$', views.search, name='search'),
)

blist/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site

def validate_full(value):
	if value is None:
		raise ValidationError('You cannot leave Item Name blank!')

# Create your models here.
class BL(models.Model):
	owner = models.ForeignKey(settings.AUTH_USER_MODEL)
	name = models.CharField(max_length=50)
	favorite = models.BooleanField(default=False)

	def get_absolute_url(self):
		return reverse('blist:items', args=[self.id,])

	def get_share_url(self):
		return 'http://' + str(Site.objects.get(id=1)) + str(self.get_absolute_url()) + 'share'

	def get_editors(self):
		return ', '.join(self.sharedlist_set.values_list('name', flat=True))

	def __unicode__(self):
		return self.name

class Item(models.Model):
	bucket = models.ForeignKey(BL)
	item_value = models.CharField(max_length=200, validators=[validate_full])
	item_url = models.URLField(max_length=200,null=True,blank=True)
	item_desc = models.CharField(max_length=500,null=True,blank=True)
	finish = models.DateField(null=True,blank=True)

	def __unicode__(self):
		return self.item_value

class SharedList(models.Model):
	name = models.CharField(max_length=100)
	bucket = models.ForeignKey(BL)

	def __unicode__(self):
		return str(self.name) + " can edit " + str(self.bucket)

blist/forms.py
from django.forms import ModelForm, Textarea
from django import forms

from blist.models import BL, Item, SharedList

class ItemForm(ModelForm):
	class Meta:
		model = Item
		fields = ('item_value','item_url','item_desc')
		widgets = {
			'item_value':forms.TextInput(attrs={
				'placeholder':'Item Name',
				'class':'form-control',
				}),
			'item_desc': Textarea(attrs={
				'placeholder':'Description (optional)',
				'class':'form-control',
				}),
			'item_url':forms.TextInput(attrs={
				'placeholder':'URL (optional)',
				'class':'form-control',
				}),
			}

class BLForm(ModelForm):
	class Meta:
		model = BL
		fields = ('name',)
		widgets = {
			'name': forms.TextInput(attrs={
				'placeholder':'List Name',
				'class':'form-control',
				}),
			}

class SharedForm(ModelForm):
	class Meta:
		model = SharedList
		fields = ('name',)
		widgets = {
			'name': forms.TextInput(attrs={
				'placeholder':'Username',
				'class':'form-control',
				'id':'username',
				}),
			}

blist/views.py
import json

from datetime import datetime

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string
from django.contrib.auth.models import User

from blist.models import BL, Item, SharedList
from blist.forms import ItemForm, BLForm, SharedForm

# Create your views here.
@login_required
def index(request, faves=False):
	if faves == False:
		bucket_list = BL.objects.filter(owner=request.user)
	else:
		bucket_list = BL.objects.filter(owner=request.user,favorite=True)
	if request.method == 'POST':
		if request.is_ajax():
			add_list_form = BLForm(request.POST)
			if add_list_form.is_valid():
				bucket_list = add_list_form.save(commit=False)
				bucket_list.owner = request.user
				bucket_list.save()
				return HttpResponse(render_to_string('blist/lists.html', {'bucket':bucket_list}))
			else:
				return HttpResponse(status=400)
		else:
			return HttpResponse(status=403)
	else:
		add_list_form = BLForm()
	return render(request,'blist/index.html', {'bucket_list':bucket_list,'form':add_list_form,})

@login_required
def items(request, bucket_id):
	bucket = get_object_or_404(BL,pk=bucket_id,owner=request.user)
	editors = SharedList.objects.filter(bucket=bucket.id).values_list('name',flat=True)
	users = User.objects.all().values_list('username',flat=True)
	if request.method == 'POST':
		if request.is_ajax():
			add_form = ItemForm(request.POST)
			if add_form.is_valid():
				bucket_item = add_form.save(commit=False)
				bucket_item.bucket = bucket
				bucket_item.save()
				return HttpResponse(render_to_string('blist/item_table.html', {'item':bucket_item,'bucket':bucket}))
			else:
				return HttpResponse(status=400)
	else:
		add_form = ItemForm()
		shared_form = SharedForm()
	return render(request,'blist/items.html', {
		'bucket':bucket,
		'form':add_form,
		'shared':shared_form,
		'editors':editors,
		'existing':json.dumps(list(editors)),
		'users':json.dumps(list(users)),})

@login_required
def add_editor(request, bucket_id):
	bucket = get_object_or_404(BL,pk=bucket_id,owner=request.user)
	if request.method == 'POST':
		form = SharedForm(request.POST)
		if request.is_ajax():
			if form.is_valid():
				editor = form.save(commit=False)
				editor.bucket = bucket
				editor.save()
				return HttpResponse(status=200)
			else:
				return HttpResponse(status=400)
	return HttpResponse(status=200)

@login_required
def details(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id,bucket__owner=request.user)
	return render(request,'blist/details.html', {'item':item,})

@login_required
def delete_item(request, bucket_id, item_id):
	if request.is_ajax():
		item = get_object_or_404(Item,pk=item_id)
		item.delete()
		return HttpResponse(status=200)
	return HttpResponse(status=403)

@login_required
def delete_bucket(request, bucket_id):
	if request.is_ajax():
		bucket = get_object_or_404(BL,pk=bucket_id,owner=request.user)
		bucket.delete()
		return HttpResponse(status=200)
	return HttpResponse(status=403)

@login_required
def mod_favorite(request, bucket_id):
	if request.is_ajax():
		bucket = get_object_or_404(BL,pk=bucket_id,owner=request.user)
		bucket.favorite = not bucket.favorite
		bucket.save()
		return HttpResponse(status=200)
	return HttpResponse(status=403)

@login_required
def finish(request, bucket_id, item_id):
	if request.is_ajax():
		item = get_object_or_404(Item,pk=item_id)
		if item.finish != None:
			item.finish = None
		else:
			item.finish = datetime.now()
		item.save()
		return HttpResponse(status=200)
	return HttpResponse(status=403)

@login_required
def search(request):
	error = False
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			error = True
		else:
			item = Item.objects.filter(item_value__icontains=q,bucket__owner=request.user)
			return render(request, 'blist/search.html', {'items':item,'query':q})
	return render(request, 'blist/search.html', {'error':error})

# Shared Views

@login_required
def shared_index(request):
	shared = SharedList.objects.filter(name=request.user).values_list('bucket_id',flat=True)
	bls = []
	for bl in shared:
		current = BL.objects.filter(pk=bl)
		bls.append(current[0])
	return render(request,'blist/shared_index.html',{'lists':bls if len(bls) else None})

@login_required
def shared_list(request, bucket_id):
	bucket = get_object_or_404(BL,pk=bucket_id)
	if request.method == 'POST':
		if request.is_ajax():
			form = ItemForm(request.POST)
			if form.is_valid():
				bucket_item = form.save(commit=False)
				bucket_item.bucket = bucket
				bucket_item.save()
				return HttpResponse(render_to_string('blist/shared_items_table.html', {'item':bucket_item,'bucket':bucket}))
			else:
				return HttpResponse(status=400)
	else:
		form = ItemForm()
	return render(request,'blist/shared_items.html',{'bucket':bucket,'form':form})

@login_required
def shared_detail(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	return render(request,'blist/shared_detail.html', {'item':item,})

# Anonymous Views

def share(request, bucket_id):
	bucket = get_object_or_404(BL,pk=bucket_id)
	return render(request,'blist/share.html', {'bucket':bucket,})

def share_details(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	return render(request,'blist/share_details.html', {'item':item,})

def register(request):
	if request.user.is_authenticated():
		HttpResponseRedirect('/blist/')
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			return HttpResponseRedirect("/blist/")
	else:
		form = UserCreationForm()
	return render(request, "blist/register.html", {'form': form,})

# X-Editable Views

@login_required
def xu_desc(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	if request.method == 'POST':
		if request.is_ajax():
			new_desc = request.POST.get('value')
			item.item_desc = new_desc
			item.save()
			return HttpResponse(status=200)

@login_required
def xu_url(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	if request.method == 'POST':
		if request.is_ajax():
			new_url = request.POST.get('value')
			item.item_url = new_url
			item.save()
			return HttpResponse(status=200)

@login_required
def xu_name(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	if request.method == 'POST':
		if request.is_ajax():
			new_name = request.POST.get('value')
			item.item_value = new_name
			item.save()
			return HttpResponse(status=200)

@login_required
def xu_date(request, bucket_id, item_id):
	item = get_object_or_404(Item,pk=item_id)
	if request.method == 'POST':
		if request.is_ajax():
			new_date = request.POST.get('value')
			item.finish = new_date
			item.save()
			return HttpResponse(status=200)

blist/templates/blist/details.html
{% extends "base.html" %}

{% block title %} | {{ item.item_value }}{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading"><h4>{{ item.bucket }} | {{ item.item_value }}</h4></div>

	<div class='panel-body'>
		<table class='table-striped table-condensed' width="100%">
			<tr>
				<th width='20%'><b>Name:</b></th>
				<td width='80%'><a href="#" class='iname'>{{ item.item_value }}</a></td>
			</tr>
			{% if item.finish != NULL %} 
			<tr>
				<th width='20%'><b>Completed:</b></th>
				<td width='80%'><a href="#" class='idate'>{{ item.finish }}</a></td>
			</tr>
			{% endif %}
			<tr>
				<th width='20%'><b>URL: </b></th>
				<td width='80%'><a href="#" class="iurl">{{ item.item_url }}</a></td>
			</tr>
			<tr>
				<th width='20%'><b>Description: </b></th>
				<td width='80%'><a href="#" class="idesc">{{ item.item_desc }}</a></td>
			</tr>
		</table>
	</div>
	<div class='panel-body'>
		<div class="alert alert-success" role="alert"><p>Click on a field to edit its entry</p></div>
	</div>
</div>

<a href="{% url 'blist:items' item.bucket.id %}">
	<button type="button" class="btn btn-primary">
    	<span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
	</button>
</a>

<script>
$('.iname').editable({
	type: 'text',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_name" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	validate: function(value) {
    	if($.trim(value) == '') {
    		return 'Please enter an item name';
    	}
    },
});

$('.idate').editable({
	type: 'combodate',
	format: 'YYYY-MM-DD',
	viewformat: 'MMM. DD, YYYY',
	template: 'MMM / DD / YYYY',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_date" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}", 
});

$('.idesc').editable({
	type: 'textarea',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_desc" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	emptytext: "No description"
});

$('.iurl').editable({
	type: 'url',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_url" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	emptytext: 'No URL'
});
</script>

{% endblock %}

blist/templates/blist/item_table.html
<tr>
    <td style="text-align:center" width="5%">
    {% if item.finish == none %}
        <a href="javascript:void(0);" oid='{{ item.pk }}' fin='0'>
            <span class="glyphicon glyphicon-unchecked finish" aria-hidden="true" oid='{{ item.pk }}' bid='{{ item.bucket.pk }}'></span>
        </a></td>
        <td width='90%'><a href="{% url 'blist:details' bucket.pk item.pk %}">{{ item.item_value }}</a></td>
    {% else %}
        <a href="javascript:void(0);" oid='{{ item.pk }}' fin='1'>
            <span class="glyphicon glyphicon-check finish" aria-hidden="true" oid='{{ item.pk }}' bid='{{ item.bucket.pk }}' data-placement="left" data-toggle="tooltip" title="Completed: {{ item.finish }}"></span> 
        </a></td>
        <td width='90%'><a href="{% url 'blist:details' bucket.pk item.pk %}">{{ item.item_value }}</a></td>
    {% endif %}

    <td width="5%" style='text-align:center'>
        <span class="glyphicon glyphicon-trash delete" aria-hidden="true" data-toggle="modal" data-target="#delete" oid='{{ item.pk }}' bid='{{ item.bucket.pk }}'></span>
    </td>
</tr>

blist/templates/blist/items.html
{% extends "base.html" %}

{% block title %} | {{ bucket.name }}{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading"><h4>{{ bucket.name }}</h4></div>

    <div class='panel-body'>
        <table class='table table-striped table-condensed' id='ItemTable'>
            <tr>
                <th style="text-align:center" width="5%">Done</th>
                <th width='90%'>Name</th>
                <th style='text-align:center' width="5%">Delete</th>
            {% for item in bucket.item_set.all %}
                {% include 'blist/item_table.html' %}
            {% endfor %}
        </table>
    </div>
</div>

<!-- Add Item Form -->

<div class="panel-group" role="tablist" aria-multiselectable="true">
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <a data-toggle="collapse" href="#collapse-add" aria-expanded="true" aria-controls="collapse-add"><b>Add Item</b></a>
        </div>

        <div id="collapse-add" class="panel-collapse collapse" role="tabpanel">
            <div class='panel-body' id="AddBox">
                <form action="." method="post" id='AddItem'>
                    {% csrf_token %}
                    {{ form.item_value }}
                    <br>
                    {{ form.item_url }}
                    <br>
                    {{ form.item_desc }}
                    <br>
                    <input type="submit" class="btn btn-primary" value='Add Item'>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Add Editor Form -->
<div class="panel-default">
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <b>Add Editor</b>
        </div>

        <div class='panel-body' id='editorPanel'>
            <form action="{% url 'blist:add_editor' bucket.pk %}" method="post" id='addEditor'>
                {% csrf_token %}
                <div class='input-group'>
                    {{ shared.name }}
                    <span class='input-group-btn'>
                        <button type='submit' class='btn btn-default'>
                            <span class="glyphicon glyphicon-plus"></span>
                        </button>
                    </span>
                </div>
            </form>
            <br>
            <ul class='list-group' id='editors'>
            {% for name in editors %}
                <li class='list-group-item'>{{ name }}</li>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Anonymous Share Panel -->

<div class="panel panel-default">
    <div class="panel-heading"><b>Share This List</b></div>
    <div class="panel-body">
        <input type='text' value='{{ bucket.get_share_url }}' class='form-control' readonly></input>
    </div>
</div>

<a href="/blist/"><button type="button" class="btn btn-primary">
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
</button></a>

<!-- Modal dialogs -->

<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="dellist" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="dellist">Delete?</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger confirm" data-dismiss='modal'>Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Additional Javascript -->

<script>
$('#addEditor').submit(function() {
    current =  '{{request.user }}';
    editors = '{{ existing|safe }}';
    users = '{{ users|safe }}';
    addition = $('#username').val();
    if (users.indexOf(addition) == -1) {
        $('div[role=alert]').remove();
        $('#username').val('');
        $('#editorPanel').prepend('<div class="alert alert-danger" role="alert"><p>That username does not exist!</p></div>');
        return false
    } else if ($('#username').val() == current) {
        $('div[role=alert]').remove();
        $('#username').val('');
        $('#editorPanel').prepend('<div class="alert alert-danger" role="alert"><p>You already have editing privileges for this list!</p></div>');
        return false
    } else if (editors.indexOf(addition) > -1) {
        $('div[role=alert]').remove();
        $('#editorPanel').prepend('<div class="alert alert-danger" role="alert"><p>'+addition+' already has editing privileges for this list!</p></div>');
        $('#username').val('');
        return false
    } else {
        $.ajax({
            type: $('#addEditor').attr('method'),
            url: $('#addEditor').attr('action'),
            data: $('#addEditor').serialize(),
            success: function() {
                $('div[role=alert]').remove();
                $('#editors').append('<li class="list-group-item">'+addition+'</li>');                
                $('#username').val('');
            },
        });
        return false;
    };
});

$('#AddItem').submit(function() {
    $.ajax({
        type: $('#AddItem').attr('method'),
        url: $('#AddItem').attr('action'),
        data: $('#AddItem').serialize(),
        success: function(data) {
            $('div[role=alert]').remove();
            $('#AddItem')[0].reset();
            $('#ItemTable').append(data);
            $('.idesc, .iurl').editable();
        },
        error: function() {
            $('#AddBox').append('<br><div class="alert alert-danger" role="alert"><p>Item Name is required</p></div>');
        },
    });
    return false;
});

$('#delete').on('click', '.confirm', function() {
    $.ajax({
        url: '/blist/' + $bid + '/' + $oid + '/delete/', 
        method: 'POST',
        success: function() {
            $('.delete[oid=' + $oid + ']').closest('tr').remove();
        },
    });
});

$('#ItemTable').on('click', '.delete', function() {
    $oid = $(this).attr('oid');
    $bid = $(this).attr('bid');
});

$('#ItemTable').on('click', '.finish', toggledone);
</script>

{% endblock %}

blist/templates/blist/register.html
{% extends "base.html" %}

{% block title %} | Register{% endblock %}

{% block anon %}

<div class='col-md-offset-3 col-md-6'>
	<div class="panel panel-default">
	    <div class="panel-heading"><h4>Create Account</h4></div>
	</div>

	<div class="panel panel-default">
	    <div class="panel-body">
	    	<form action="" method="post" class="form-horizontal" role='form'>
				{% csrf_token %}
				<table class="table table-condensed" style="padding:5px">
					<tr>
	    				<td>{{ form.username.label_tag }}</td>
	    				<td>{{ form.username }}</td>
					</tr>
					<tr>
	    				<td>{{ form.password1.label_tag }}</td>
	    				<td>{{ form.password1 }}</td>
					</tr>
					<tr>
	    				<td>{{ form.password2.label_tag }}</td>
	    				<td>{{ form.password2 }}</td>
					</tr>
				</table>
				<button type="button submit" class="btn btn-primary">
					Create Account
				</button>
			</form>
	    </div>
	</div>
</div>

{% endblock %}

blist/templates/blist/share.html
{% extends "base.html" %}

{% block title %} | {{ bucket.name }}{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading"><h4>{{ bucket.name }}</h4></div>

    <div class='panel-body'>
        <ul class='list-group'>
            {% for item in bucket.item_set.all %}
                <li class='list-group-item'>
                    {% if item.finish == none %}
                        <span class="glyphicon glyphicon-unchecked finish" aria-hidden="true"></span> 
                        <a href="{% url 'blist:sdetails' bucket.pk item.pk %}">{{ item.item_value }}</a> 
                    {% else %}
                        <span class="glyphicon glyphicon-check finish" aria-hidden="true" data-placement="left" data-toggle="tooltip" title="Completed: {{ item.finish }}"></span> 
                        <a href="{% url 'blist:sdetails' bucket.pk item.pk %}">{{ item.item_value }}</a> 
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading"><b>Share This List</b></div>
    <div class="panel-body">
        <div class='well well-sm share'></div>
    </div>
</div>

<!-- Additional Javascript -->

<script>
var share = window.location.href;

$(document).ready(function(){
    $('.share').append(share);
});
</script>

{% endblock %}

blist/templates/blist/shared_detail.html
{% extends "base.html" %}

{% block title %} | {{ item.item_value }}{% endblock %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading"><h4>{{ item.bucket }} | {{ item.item_value }}</h4></div>

	<div class='panel-body'>
		<table class='table-striped table-condensed' width="100%">
			<tr>
				<th width='20%'><b>Name:</b></th>
				<td width='80%'><a href="#" class='iname'>{{ item.item_value }}</a></td>
			</tr>
			{% if item.finish != NULL %} 
			<tr>
				<th width='20%'><b>Completed:</b></th>
				<td width='80%'><a href="#" class='idate'>{{ item.finish }}</a></td>
			</tr>
			{% endif %}
			<tr>
				<th width='20%'><b>URL: </b></th>
				<td width='80%'><a href="#" class="iurl">{{ item.item_url }}</a></td>
			</tr>
			<tr>
				<th width='20%'><b>Description: </b></th>
				<td width='80%'><a href="#" class="idesc">{{ item.item_desc }}</a></td>
			</tr>
		</table>
	</div>
	<div class='panel-body'>
		<div class="alert alert-success" role="alert"><p>Click on a field to edit its entry</p></div>
	</div>
</div>

<a href="{% url 'blist:shared_list' item.bucket.id %}">
	<button type="button" class="btn btn-primary">
    	<span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
	</button>
</a>

<script>
$('.iname').editable({
	type: 'text',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_name" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	validate: function(value) {
    	if($.trim(value) == '') {
    		return 'Please enter an item name';
    	}
    },
});

$('.idate').editable({
	type: 'combodate',
	format: 'YYYY-MM-DD',
	viewformat: 'MMM. DD, YYYY',
	template: 'MMM / DD / YYYY',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_date" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}", 
});

$('.idesc').editable({
	type: 'textarea',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_desc" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	emptytext: "No description"
});

$('.iurl').editable({
	type: 'url',
	pk: '{{ item.pk }}',
	url: '{% url "blist:xu_url" item.bucket.pk item.pk %}',
	params: "{csrfmiddlewaretoken:'{{csrf_token}}'}",
	emptytext: 'No URL'
});
</script>

{% endblock %}

blist/templates/blist/shared_lists_table.html
<div class='panel panel-default'>
    <div class='panel-heading'>
        <a href="{% url 'blist:shared_list' bucket.id %}"><b>{{ bucket.name }}</b></a> | Owner: {{ bucket.owner }}
        <span class="glyphicon glyphicon-chevron-down pull-right" aria-hidden="true" data-toggle="collapse" href="#{{ bucket.pk }}" aria-controls="{{ bucket.pk }}"></span>
    </div>
    <div id="{{ bucket.pk }}" class="panel-collapse collapse" role="tabpanel">
        <ul class='list-group itemlist'>
        {% for item in bucket.item_set.all %}
            <li class='list-group-item'>
                {% if item.finish == none %} 
                    <a href="javascript:void(0);" oid='{{ item.pk }}' fin='0'>
                        <span class="glyphicon glyphicon-unchecked finish" aria-hidden="true" oid='{{ item.pk }}' bid='{{ item.bucket.pk }}'></span>
                    </a> {{ item.item_value }}
                {% else %}
                    <a href="javascript:void(0);" oid='{{ item.pk }}' fin='1'>
                        <span class="glyphicon glyphicon-check finish" aria-hidden="true" oid='{{ item.pk }}' bid='{{ item.bucket.pk }}' title="Completed: {{ item.finish }}" data-placement="left" data-toggle="tooltip"></span>
                    </a> {{ item.item_value }}
                {% endif %}
            </li>
        {% endfor %}
        </ul>
    </div>
</div>